{
 "title": "网络设备大屏",
 "description": "Created a network dashboard to monitor device status + Interfaces.  Hopefully, it helps the community. ",
 "tags": [
  "Zabbix",
  "NETWORK"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "DATA_SOURCE",
    "label": "监控实例:",
    "query": "alexanderzobnin-zabbix-datasource"
   },
   { "name": "Group", "label": "分组:", "query": "*" },
   { "name": "Host", "label": "名称:", "query": "$Group.*" }
  ]
 },
 "panels": [
  {
   "title": "Power Supply",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "Power supply" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "Sw1, PS1 Normal, RPS NotExist: Power supply status"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "Status" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "启动时间",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Status" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "Uptime" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "Temperature" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "SW#1, Sensor#1, GREEN : Temperature status"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "#1: CPU utilization" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "slaProperty": "sla",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "ICMP Response Time",
   "type": "graph",
   "gridPos": { "h": 4, "w": 18, "x": 3, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Status" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "ICMP response time" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "Processor: Memory utilization" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "slaProperty": "sla",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Interface Incoming Traffic bits/errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "application": { "filter": "$Interface" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "/(?:Bits\\ received)/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "$Interface" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "/(?:Inbound\\ packets\\ with\\ errors)/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Interface Outgoing Traffic bits/errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "application": { "filter": "$Interface" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "/(?:Bits\\ sent)/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "$Interface" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "/(?:Outbound\\ packets\\ with\\ errors)/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}