# Generated by Django 2.2.6 on 2020-12-02 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_verifyinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProxy',
        ),
        migrations.AlterField(
            model_name='userproperty',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='account.User'),
        ),
        migrations.AlterField(
            model_name='verifyinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User'),
        ),
    ]
