# Generated by Django 2.2.6 on 2021-05-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', 'init_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandblockhistory',
            name='intercept_command',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='commandblocklist',
            name='block_type',
            field=models.CharField(choices=[('cancel', '取消'), ('confirm', '确认')], default='cancel', max_length=8, verbose_name='阻断类型'),
        ),
    ]
