# Generated by Django 2.2.6 on 2020-09-21 10:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('control', '0016_auto_20200714_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='End time')),
                ('channel', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Channel name')),
                ('log_name', models.CharField(editable=False, max_length=100, unique=True, verbose_name='log name')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Start time')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Is finished')),
                ('user', models.CharField(max_length=100, verbose_name='username')),
                ('guacamole_client_id', models.CharField(blank=True, editable=False, max_length=100, verbose_name='Gucamole channel name')),
                ('tag', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tag')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='control.AgentAdmin', verbose_name='Server')),
            ],
            options={
                'db_table': 'control_terminal_log',
                'ordering': ['-start_time'],
            },
        ),
    ]
