# Generated by Django 2.2.6 on 2020-09-25 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0002_auto_20200922_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionlog',
            name='log_name',
            field=models.CharField(editable=False, max_length=100, unique=True, verbose_name='Log name'),
        ),
        migrations.AlterField(
            model_name='sessionlog',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.AgentAdmin', verbose_name='Server'),
        ),
    ]
