# Generated by Django 2.2.6 on 2020-10-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0003_auto_20200925_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionlog',
            name='log_name',
            field=models.CharField(editable=False, max_length=100, verbose_name='Log name'),
        ),
    ]
