# Generated by Django 2.2.6 on 2020-11-05 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0004_auto_20201009_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionlog',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='control.AgentAdmin', verbose_name='Server'),
        ),
    ]
