# Generated by Django 2.2.6 on 2020-11-05 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0005_auto_20201105_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandlog',
            name='log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='terminal.SessionLog', verbose_name='Terminal Log'),
        ),
        migrations.AlterField(
            model_name='sessionlog',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.AgentAdmin', verbose_name='Server'),
        ),
    ]
