# Generated by Django 2.2.6 on 2020-11-07 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0006_auto_20201105_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandBlockList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=255, verbose_name='指令名称')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='date time')),
                ('block_type', models.CharField(choices=[('cancle', '取消'), ('confirm', '确认')], default='cancle', max_length=8, verbose_name='阻断类型')),
                ('block_info', models.CharField(max_length=255, verbose_name='阻断提示信息')),
            ],
            options={
                'db_table': 'control_command_blocklist',
                'ordering': ['-datetime'],
            },
        ),
        migrations.AlterField(
            model_name='commandlog',
            name='log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='terminal.SessionLog', verbose_name='Terminal Log'),
        ),
    ]
