# Generated by Django 2.2.6 on 2020-11-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0007_auto_20201107_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandBlockHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=255, verbose_name='指令')),
                ('hostname', models.CharField(max_length=255, verbose_name='服务器IP')),
                ('user', models.CharField(max_length=32, null=True, verbose_name='用户名')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='date time')),
            ],
        ),
    ]
