# Generated by Django 2.2.6 on 2020-11-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0008_commandblockhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandblockhistory',
            name='status',
            field=models.CharField(choices=[('y', '执行'), ('n', '未执行')], default='n', max_length=8, verbose_name='指令是否执行'),
        ),
    ]
