# Generated by Django 2.2.6 on 2020-11-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0009_commandblockhistory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandblockhistory',
            name='block_type',
            field=models.CharField(max_length=8, null=True, verbose_name='阻断类型'),
        ),
    ]
