# Generated by Django 2.2.6 on 2020-11-13 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0010_commandblockhistory_block_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commandblockhistory',
            options={'ordering': ['-datetime']},
        ),
        migrations.AlterModelTable(
            name='commandblockhistory',
            table='control_command_blockhistroy',
        ),
    ]
