# Generated by Django 2.2.6 on 2020-12-02 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0012_auto_20201119_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionlog',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.AgentAdmin', verbose_name='Server'),
        ),
    ]
