# Generated by Django 2.2.6 on 2020-12-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0013_auto_20201202_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandblockhistory',
            name='opt_user',
            field=models.CharField(max_length=32, null=True, verbose_name='操作用户'),
        ),
    ]
