"""
Copyright © 2012-2020 OpsAny. All Rights Reserved. 河南我买云信息技术有限公司版权所有
""" # noqa
# Generated by Django 2.2.6 on 2020-02-26 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('ip', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=20)),
                ('username', models.CharField(default='root', max_length=10)),
                ('system_type', models.CharField(default='linux', max_length=20)),
                ('ssh_port', models.CharField(max_length=20)),
                ('control_type', models.CharField(max_length=20)),
                ('password', models.CharField(default='', max_length=30)),
                ('key_url', models.CharField(default='', max_length=125)),
            ],
            options={
                'db_table': 'agent_admin',
            },
        ),
        migrations.CreateModel(
            name='ControllerAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=16, unique=True)),
                ('type', models.CharField(max_length=10)),
                ('api1', models.CharField(max_length=50)),
                ('api2', models.CharField(max_length=50)),
                ('username1', models.CharField(max_length=20)),
                ('username2', models.CharField(max_length=20)),
                ('password1', models.CharField(max_length=20)),
                ('password2', models.CharField(max_length=20)),
                ('port1', models.CharField(default='', max_length=20)),
                ('port2', models.CharField(default='', max_length=20)),
                ('state1', models.BooleanField(default=True)),
                ('state2', models.BooleanField(default=True)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'controller_admin',
            },
        ),
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=16, unique=True)),
                ('type', models.CharField(max_length=10)),
                ('describe', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'host_group',
            },
        ),
        migrations.CreateModel(
            name='HostList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('ip', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=30)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.HostGroup')),
            ],
            options={
                'db_table': 'host_list',
            },
        ),
    ]
