"""
Copyright © 2012-2020 OpsAny. All Rights Reserved. 河南我买云信息技术有限公司版权所有
""" # noqa
# Generated by Django 2.2.6 on 2020-02-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentadmin',
            name='agent_state',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='agentadmin',
            name='key_url',
            field=models.CharField(default='', max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='agentadmin',
            name='password',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
