"""
Copyright © 2012-2020 OpsAny. All Rights Reserved. 河南我买云信息技术有限公司版权所有
""" # noqa
# Generated by Django 2.2.6 on 2020-02-28 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_auto_20200227_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentadmin',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.HostGroup'),
        ),
        migrations.DeleteModel(
            name='HostList',
        ),
    ]
