"""
Copyright © 2012-2020 OpsAny. All Rights Reserved. 河南我买云信息技术有限公司版权所有
""" # noqa
# Generated by Django 2.2.6 on 2020-03-02 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_auto_20200228_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentadmin',
            name='controller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.ControllerAdmin'),
        ),
    ]
