"""
Copyright © 2012-2020 OpsAny. All Rights Reserved. 河南我买云信息技术有限公司版权所有
""" # noqa
# Generated by Django 2.2.6 on 2020-03-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_agentadmin_controller'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentadmin',
            name='platform',
            field=models.CharField(default='control', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='agentadmin',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
