"""
Copyright © 2012-2020 OpsAny. All Rights Reserved. 河南我买云信息技术有限公司版权所有
""" # noqa
# Generated by Django 2.2.6 on 2020-03-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_auto_20200318_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentadmin',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
