"""
Copyright © 2012-2020 OpsAny. All Rights Reserved. 河南我买云信息技术有限公司版权所有
""" # noqa
# Generated by Django 2.2.6 on 2020-03-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_auto_20200318_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentadmin',
            name='host_type',
            field=models.CharField(default='SERVER', max_length=30, null=True),
        ),
    ]
