"""
Copyright © 2012-2020 OpsAny. All Rights Reserved. 河南我买云信息技术有限公司版权所有
""" # noqa
# Generated by Django 2.2.6 on 2020-03-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_agentadmin_host_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentadmin',
            name='system_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='agentadmin',
            name='system_type',
            field=models.CharField(default='Linux', max_length=20),
        ),
    ]
