# Generated by Django 2.2.6 on 2020-05-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_auto_20200324_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentadmin',
            name='ip_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
