# Generated by Django 2.2.6 on 2020-05-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0009_agentadmin_ip_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentadmin',
            name='zabbix_agent_state',
            field=models.CharField(default='未连接', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='agentadmin',
            name='zabbix_host_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
