# Generated by Django 2.2.6 on 2020-05-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0010_auto_20200526_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetWorkEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=50, null=True)),
                ('equipment_type', models.CharField(default='local', max_length=50)),
                ('team_name', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('describe', models.CharField(max_length=50)),
            ],
        ),
    ]
