# Generated by Django 2.2.6 on 2020-05-28 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0011_networkequipment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='networkequipment',
            table='net_equipment',
        ),
    ]
