# Generated by Django 2.2.6 on 2020-05-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0012_auto_20200528_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkequipment',
            name='zabbix_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='networkequipment',
            name='zabbix_status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='networkequipment',
            name='describe',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='networkequipment',
            name='equipment_type',
            field=models.CharField(default='SWITCH', max_length=50),
        ),
        migrations.AlterField(
            model_name='networkequipment',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='networkequipment',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='networkequipment',
            name='team_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='networkequipment',
            name='user',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
