# Generated by Django 2.2.6 on 2020-05-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0013_auto_20200531_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkequipment',
            name='zabbix_status',
            field=models.CharField(default='未连接', max_length=50),
        ),
    ]
