# Generated by Django 2.2.6 on 2020-07-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0014_auto_20200531_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentadmin',
            name='add_type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
