# Generated by Django 2.2.6 on 2020-07-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0015_agentadmin_add_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentadmin',
            name='ssh_port',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
