# Generated by Django 2.2.6 on 2020-08-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0016_auto_20200714_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentadmin',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='controlleradmin',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
