# Generated by Django 2.2.6 on 2020-08-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0017_auto_20200824_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=255)),
                ('ch_name', models.CharField(max_length=20)),
                ('role', models.IntegerField()),
                ('icon_url', models.CharField(default='/static/user_icon/edfb99ee-08d6-41b8-ac5f-117fb86b0912.png', max_length=255)),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
    ]
