# Generated by Django 2.2.6 on 2020-08-27 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0018_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCanSeeAgentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.AgentAdmin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.UserInfo')),
            ],
            options={
                'db_table': 'user_can_see_agent',
            },
        ),
    ]
