# Generated by Django 2.2.6 on 2020-08-28 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0019_usercanseeagentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentadmin',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_agent', to='control.HostGroup'),
        ),
    ]
