# Generated by Django 2.2.6 on 2020-09-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0020_auto_20200828_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentadmin',
            name='show_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
