# Generated by Django 2.2.6 on 2020-09-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0021_agentadmin_show_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostgroup',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
