# Generated by Django 2.2.6 on 2020-09-27 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0022_auto_20200915_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlleradmin',
            name='zabbix_password',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='controlleradmin',
            name='zabbix_state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='controlleradmin',
            name='zabbix_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='controlleradmin',
            name='zabbix_username',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='AgentVariableModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('describe', models.CharField(max_length=255)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.AgentAdmin')),
            ],
            options={
                'db_table': 'agent_variable_model',
            },
        ),
        migrations.CreateModel(
            name='AgentTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('temp_id', models.CharField(max_length=100)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.AgentAdmin')),
            ],
            options={
                'db_table': 'agent_template',
            },
        ),
        migrations.CreateModel(
            name='AgentSignModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.AgentAdmin')),
            ],
            options={
                'db_table': 'agent_sign_model',
            },
        ),
    ]
