# Generated by Django 2.2.6 on 2020-09-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0026_auto_20200927_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttemplate',
            name='temp_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='agenttemplate',
            name='temp_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
