# Generated by Django 2.2.6 on 2020-09-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0027_auto_20200928_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentadmin',
            name='zabbix_agent_state',
            field=models.BooleanField(default=True),
        ),
    ]
