# Generated by Django 2.2.6 on 2020-10-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0028_auto_20200928_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentadmin',
            name='username',
            field=models.CharField(default='root', max_length=32),
        ),
    ]
