# Generated by Django 2.2.6 on 2020-11-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0029_auto_20201030_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentadmin',
            name='ssh_port',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agentadmin',
            name='username',
            field=models.CharField(default='root', max_length=255),
        ),
    ]
