# Generated by Django 2.2.6 on 2020-11-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0031_agentadmin_ssh_key_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentadmin',
            name='ssh_type',
            field=models.CharField(default='password', max_length=20),
        ),
    ]
