# Generated by Django 2.2.6 on 2020-11-13 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0033_useragentmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCanSeeAgentModel',
        ),
    ]
