# Generated by Django 2.2.6 on 2020-11-19 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0034_delete_usercanseeagentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHostGroupModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_user', to='control.HostGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_group', to='control.UserInfo')),
            ],
            options={
                'db_table': 'user_host_group',
            },
        ),
    ]
