# Generated by Django 2.2.6 on 2020-11-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0035_userhostgroupmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='password',
            field=models.CharField(default='', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
