# Generated by Django 2.2.6 on 2020-12-02 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0036_auto_20201124_1725'),
    ]

    operations = [
    ]
