# Generated by Django 2.2.6 on 2020-12-03 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0038_auto_20201202_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='password',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
