# Generated by Django 2.2.6 on 2021-04-13 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0039_auto_20201203_0057'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agentadmin',
            unique_together={('ip', 'name')},
        ),
    ]
